---
title: "class-2019-11-14"
author: "Hanif Wicaksono"
date: "11/14/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#Load libraries & data

library(googlesheets4)
library(tidyverse)

sheets_deauth()

survey <-
  read_sheet("1QA_Xv9tAbKhwFdQpnVa2hTjhEdg5zAl4WY5EVanWSo0")

```

```{r}

#Explore the data 

glimpse(survey)

survey %>%
  sample_n(10)

```

```{r}

# Plot the data

ggplot(survey, aes(x = dem_adv, y = dvote)) +
  geom_jitter(height = .2, width = .2, alpha = .2) +
  geom_smooth(method = "lm", se = FALSE)

# Build regression model
# Explain democrat vote with gender

glm_1 <-
  glm(data = survey, formula = dvote ~ female, family = "binomial")

print(glm_1)
summary(glm_1)

```

```{r}

# Graphical relationship between dvote and female

survey %>%
  ggplot(aes(x = female, y = dvote)) +
  geom_jitter(height = .2, width = .2, alpha = .2) +
  geom_smooth(method = "glm", method.args = list(family = "binomial"), se = FALSE)

# Notice slope is lower than lm model
```

